
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZGgwajM5US9pVll3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1UWXdPVEF3TlRKYUZ3MHpOakEwTVRNd09UQTFOVEphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURXLy9nQ09VRm0wZ21FNGsrdzVNOGhEUVF0UHVoS092YXZmdFZIci9wL1FmYk9BNmxyZzBCUVljdDkKYnVFckxPY1MrS1h5NGIzVHl4Y0pEQ2VIUG03aFVBNkdRSnJnWCtRWnRMNk44NWRUTEJMV2dDTmV0MjhMdys2TApxUnViRGdZNlpUQzBwd1AwUlFGWDZxQ3RrdmhDRGlqNmhxZnhQd0pWcVJUdTJ6MG00cUZwRWRTSEJHNDl0VG8yCjRwcmhZSTI3em1waXdQT2dXU0J6dkVkVFBuUW9DWllILy9ocmg5L0dtUE5ITkp6cmpsdytjVk1peXNTbEJIdWYKclpmN1FHRWZkZEsxaGFmeFp4QkZVWGVJMDdrSStCODMvL0xGZThNQlZ1eUR3ZFpkanhLMUtaL3N2c1J0KzBHWQowQlV6eXZtZ1BjeFNJSHV4KzVZUDJWNk5tVG05QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWDNRTGhadVBSUDIrTDlwd2krUUxOTDlUMFFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREl2aXRLNCt2UAphRWRQQ3dBRXhmbDVPQk5ya1RVdnpNY1RLaklKUUl3UjdvMDRNYnd3bmk2VWVWbjB5T1pITGNpcjYxNE9ucVNCCmhQRXhrekJmenZZalh2QXFSUmc1ejFnNDNRdExSWjV5ei9QaFZUcHlCa09BT2M3UENLLzVFM1QyU2JOK3l4REoKdEJ3aGMzYXFJRnIxOHZKeEZXRGI4MFFzWHRWVVE2bUZCRUNJUkFNMUgxTVoxOHB1akZadHk4S205TXBNd3R5egpuQXpwWnBOSVBUSHYrZXZUKzcyQUwzQWFoUzZXcUtlVk5rY0plYVJEai9tdHVxMWtET1NJNWhLYnpkcXhQbkRvCnR5WURtYmlhSkRyanZVMDQ4ZDl3Uld0YVdqSWlsUklaSklOOVpOZytQV0lCRmlMRW5UWnZMa1BNZGtzSEppM0EKMkJiRFlRYlJpcTluCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e790e3ca-5ac7-43d3-b6aa-9176d1751747.ap-south-1-gw.linodelke.net:443
  name: lke592772

users:
- name: lke592772-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IldfOHFQQnJRaHZYUzZ2RGl1cEZsM2FDUzVqMExfLWtqZkhtOHlkTTktMncifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tZzl2OHciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWEzZWUwOWUtZDQxNS00NTQ5LTkxMGMtOGM0MDI1ZWIwYzY4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.fqly--rQk7UUHIHtMESXfSYuV4_pdbPGYxPOl0vyK6ETJaT9p5bA_sPYwlcTcnvh6VzEWry4-QMG07L1wjP2rKSb4BmecS4iY4zmj03Ks6yBW0PXnqpAve9gpg3IaJqhBUGLVraGVJ76GU3YRcXU_CwIlRjX1pkP-xlt5FNaAHWRrF8LZ_ONYvFbmFVSruImUQ72wKjtgkqWUwRIzBJ5oV06lpFzH45Stt2El34NOZotV33m_BeI7CE3Fxt7Nmu2vuC58Ifae45Ce2etn7ZHI6NdWnstS3MI5Z2kO1R6yuCgYGNbTIJ4PHmwmbz1Mv697FxiqJkPux6khXB09bP7EQ

contexts:
- context:
    cluster: lke592772
    namespace: default
    user: lke592772-admin
  name: lke592772-ctx

current-context: lke592772-ctx
